### ISSUE TITLE
Noob - Setup Guide

### ISSUE THREAD

**Issue by Criptonite123** [AiYinZiLeGong/PUBG-Radar#26]
Hello, not fully understanding how to setup. anyone able to make quick guide on software and steps to get it working?

Is all this installed on same PC as PUBG atm?  guessing you using a VM and if so that is still undetectable on local PUBG PC? 

Thanks in advance.

**Comment by TriHard7** [comment]
Google learn how to compile Kotlin code in <insert your IDE>.

**Comment by Dolajzis** [comment]
It would be much appreciated if anyone can write quick guide how to get this work. After days of searching I've finally found something I was looking for.
Regards

**Comment by Dolajzis** [comment]
Anyone? I've spend more than 20 hours to try to understand and get this work, but I didn't get to far. This was my base comment:

By JurishCrypter
The simplest way I can instruct:
Download arpspoof from the github link kajaaaka gave, download maven for windows, extract them to individual folders, add those folders with their binary executable to the system variable path, execute arpspoof as instructed in readme, make sure your gaming computer has winpcap (so windows winsock packets can be read as udp, tcp, arp) and simply compile and execute the jar.

What I did:
1. Downloaded arpspoof and maven
2. Uziped them
3. Copied the unziped folders to system variable path (c:\users\username\AppData\Local\Microsoft\

I'm struggling on the next step "execute arpspoof" which I have no idea how to get this done, how to execute "sudo apt-get install dsniff". Can anyone give me a hint? Thanks.

**Comment by Dolajzis** [comment]
Ok I managed to the grey screen! Few hours later from grey screen to error "No ipv4 network interface!!". One step forward two steps back. No luck with arpspoof I simply haven't found how to build it or whatever i should do with it. I'm using laptop win 10 a desktop win 10. I tried bridge connect it which didn't work because of my new little friend "No ipv4 net........" unfortunetly this error still remain after diconecting from bridge connection. Well, I don't expect any reactions or answers but I still got few questions though.

1. No ipv4 network interface??
2. arpspoof how on it?
3. wireshark how to find if game pc(winpcap installed) sending something to host pc

**Comment by Norxy** [comment]
No need to build arpspoof, just go to the release page on github and download the .exe , launch it with cmd and use it like it's explained in readme.md

**Comment by Dolajzis** [comment]
Thank you Norxy. I've managed to run it completly but with no luck. As I said I'm using win10 lap and win 10 game.I did the commands as admin, created folder for radar-dependencies, folder for arspoof. Wireshark is recieving packets from game pc. Still gray screen no matter what (Network interfaces) connection option I use. I've noticed that the first option of connection is with diffrent ip address than my game pc is, does it matter? Second option is ip address of my laptop where I running radar. To the command for radar-depencies I also added "hostIP portfilter gameIP". Did you find any solution where it's gonna run for 100%, I mean like using VM on game pc, using VM on host pc, if so which OS seems to work fine?  I'm gonna try to use tcpdum insted of wireshark now.
