### ISSUE TITLE
Dormant localplayer

### ISSUE THREAD

**Issue by M0rtale** [AiYinZiLeGong/PUBG-Radar#43]
As the title says, no matter if I run the built binary on localhost or a middle-man, the localplayer is dormant at the starting location of the map, that is the island on Erangel, and the prison in Miranmar, both facing East(If you are dormant, it will face right), and all other players render perfectly if I were to minimize the map. I have tried pull request #21 , but it didn't work, I also tried to modify the if checker according to issue #10 , but it didn't work as well...

**Comment by TheUserUnknown** [comment]
Try holding your speak button for a few seconds (default key is T)

**Comment by M0rtale** [comment]
I have tried holding the speak button for a few seconds even minutes, as stated above "I have tried pull request #21". My mic settings is on always transmit voice chat so that shouldn't be a problem...

**Comment by JayJTD** [comment]
Two things to note:
1: When you drop, theres a chance your player will appear as another player
2: Entering a vehicle puts you on the map as an enemy in a vehicle

**Comment by Pochtidruid** [comment]
same issue to me, running radar on win10x64 laptop.

**Comment by anonymousdonorus** [comment]
I can not overcome this issue. Mic always on .. Mic Push to Talk .. my player never moves from the starting point. It would not be a total loss if I could scroll away from them to other areas on the map. Middle click scroll wheel does not seem to work. The center of the map is locked on my player. Using Linux Branch on Ubuntu 17. Everything else is working great. Other players are showing up. It is just not usable because I can't zoom into where I ACTUALLY am on the map. Any fresh ideas?

**Comment by JayJTD** [comment]
@anonymousdonorus Use PubgKnowns fork, it allows for the movement of the map manually.

**Comment by Sir3x** [comment]
Guys, a i think, you cacn't get packets from GamePC to server.
Check routing once more.

**Comment by AiYinZiLeGong** [comment]
#10
