### ISSUE TITLE
Network Lag Issues while spoofing

### ISSUE THREAD

**Issue by designateddrinker** [AiYinZiLeGong/PUBG-Radar#51]
Hello all! I am using a second pc (laptop) to run the map, but my network on gaming PC really takes a hit (for every 10 steps I get teleported back 3-4 steps, discord also spikes to huge ms) whenever I start arpspoof, I am not familiar with arpspoofing, is there any way to filter sniffing/spoofing so it only sniffs pubg packets and not cause lag? Or any other solution will be much appreciated! Thank you!

**Comment by Jerry1211** [comment]
try. Connecting to the internet with wifi and connect laptop to pc using ethernet and bridge the connection

**Comment by Pochtidruid** [comment]
turn off wi-fi on laptop.

**Comment by designateddrinker** [comment]
I ll try bridging the connection, I have tried with turning off wifi and using ethernet only on both but no luck. Do I need to use VPN if I do bridge? Currently Im not using any VPN since it is already lagging like hell.

**Comment by Pochtidruid** [comment]
btw to me is discord lagging "like hell" while spoofing, so im using app on my phone
using bridge

**Comment by designateddrinker** [comment]
After bridging connections and giving different static IP to host computer, I could not run arpspoof or radar, am I missing something crucial?

**Comment by Pochtidruid** [comment]
@designateddrinker 
I solved this problem for myself, you should return the settings of ipv4 on both PCs to "receive automatically" n when i set up my laptop, i missed the moment with routing as described in the readme to the radar
without routing on middle pc arpspoof is DoSing network instead of normaly intercepting communication
do from this guide http://keepthetech.com/2016/01/enable-ip-routing-on-windows10.html and the network began to work normally

**Comment by designateddrinker** [comment]
Basically, whenever I start radar on middle pc with bridge network, it does five zero lines as usual but does not open java/map. I dont know if I am putting ip's wrong or missing something else..

**Comment by designateddrinker** [comment]
@Pochtidruid This solved my problem, thank you!
