### ISSUE TITLE
Green dot player position frozen

### ISSUE THREAD

**Issue by Dolajzis** [AiYinZiLeGong/PUBG-Radar#62]
Did anyone actually know how to fix it?? I tried udpated sniffer.kt, my mic is on set to always on. Still the player position is broken. I can see my player when i jump from the plane as white dot but after landing the green dot is still stuck on Miramar prison or Erangel island. When i play duo or squad there is no problem to see my teammate position as yellow dot. This happening when runnig on second pc. With VMware on same pc as game i haven't had this problem.

**Comment by Sir3x** [comment]
Check routing from GamePC to Server. This code get player position information from outging packets.
In case if you not get it on Second PC - gren dot stay at starting position.

**Comment by Dolajzis** [comment]
Sorry can you explain it a bit more? In my router settings i set port forwarding from pubg to my second pc. Also i needed to set pubg's TCP/UDP which im not sure if i put right numbers in it. Is this what you meant? Thanks

**Comment by Dolajzis** [comment]
Thank you! I gonna look into that, is good to know there is a solution somewhere.

**Comment by Sir3x** [comment]
Any Java exception in console ?

**Comment by Pochtidruid** [comment]
[#43](https://github.com/AiYinZiLeGong/PUBG-Radar/issues/43)

**Comment by Dolajzis** [comment]
yeah there were some, i can post them here. And #43 dindn't help me.

**Comment by niklaswi7** [comment]
Good I have figured it out now.

First its because arpspoof doenst get everything from you, so to make it work you need to setup a vpn 
using this:
On 2nd PC: (This is the pc that will run the radar)

Step 1: Search and run "cmd" - This should open the command prompt. 

Step 2: type "ipconfig" and press enter.

Step 3: Take note of your IPv4 address for VPN Settings on gaming pc. 

Step 4: Take note of your default gateway. 

Step 5: Search and run "ncpa.cpl"

Step 6: Right click your primary internet adapter, then click properties.

Step 7: Select "Internet Protocol Version 4 (TCP/IPv4)" 

Step 8: Use "Obatain an IP address automatically" and "Obtain 
DNS server address automatically"

Step 9: Click "OK"

Step 10: Uncheck "Internet Protocol Version 6 (TCP/IPv6)

Step 11: Click OK. - The PC may need up to 10 minutes for settings to refresh.

Step 12: On your keyboard, Press ALT - File will now appear on the top left.

Step 13: Click File, Then click "New Incoming Connection"

Step 14: Add someone (bottom left) - Make username and password - click ok - Then click Next.

Step 15: Checkmark "Through the Internet" - Then click Next.

Step 16: Select "Internet Protocol Version 4 (Already selected by default, make sure it is checkmarked" Then select "properties"

Step 17: Make sure "Network Access" is checked

Step 18: Under "IP address assignment" Check "Specifiy IP Addresses" 

Step 19: Use your Default Gateway from earlier, to create a proper IP range for "Specify IP addresses"
For instance: if gateway is 192.168.0.1 - use 192.168.0.2 to 192.168.0.10 for 
the ip range. - Then select "OK"

Step 20: Select Allow Access

Step 21: DONE. Now to setup the Gaming PC.



On Gaming PC: (This is the PC that will run PUBG)

Step 1: Search and run "ncpa.cpl"

Step 2: Right click your primary internet adapter, then click properties.

Step 3: Select "Internet Protocol Version 4 (TCP/IPv4)" 

Step 4: Use "Obtain an IP address automatically" and "Obtain DNS server address automatically"

Step 5: Click "OK"

Step 6: Uncheck "Internet Protocol Version 6 (TCP/IPv6)

Step 7: Click OK. - The PC may need up to 10 minutes for settings to refresh. Now close out the "Network Connections" window.

Step 8: Click your windows button (default location bottom left)

Step 9: Click the settings cog

Step 10: Click "Network & Internet"

Step 11: Click "VPN" on left side

Step 12: Click "Add a VPN Connection" on the top

Step 13: Use these settings:
VPN Provider: Windows (built-in)
Connection name: Random name
Server name or address: Insert 2nd PC IPv4 address from cmd prompt on 2nd pc
VPN type: PPTP
User name: User you made on incoming connections on 2nd pc
Password: Password you made on incoming connections on 2nd pc
Click Save.

Step 14: Connect to the VPN that you created.

Step 15: If you were able to connect, you are done! 

Remember to open port 1723 on your router to make sure you are getting internet though, that should fix the green lock

**Comment by blake567** [comment]
how open port 1723 i dont use router,

**Comment by Dolajzis** [comment]
Yeah thanks for reply, I'm running it with VPN already. I was just wondering if there's some fix to run it through arpspoof only but I couldn't get over the frozen green dot.  Does it work for you on test server though? I think is not gonna take long for BH to stop this radar.

**Comment by niklaswi7** [comment]
Its gonna take a long while for them to stop this radar since it's been around since April, its a whole server restructure they need to do to fix this.

**Comment by Dolajzis** [comment]
Ok good, it's the test server what concerns me. Looks like they are on something, especially when the radar is getting more public these days.

**Comment by niklaswi7** [comment]
the test server? dont get me wrong but i think dont think this has ever worked on the test server.

**Comment by Dolajzis** [comment]
I actually tried it few weeks back and it worked well, laggy, but now it won't let you connect to the game. Who knows, will see. Hope you're right.

**Comment by AiYinZiLeGong** [comment]
#10
