### ISSUE TITLE
Icons and no items shown

### ISSUE THREAD

**Issue by pornodog** [AiYinZiLeGong/PUBG-Radar#67]
Any legend available as to what icons i see on the map? Also, how come no items can be seen in my radar?

**Comment by pornodog** [comment]
@AiYinZiLeGong

**Comment by kajaaakaka** [comment]
I think the last pubg patch broke something.

**Comment by pateutz** [comment]
this one hase items icons @PubgKnown

**Comment by pornodog** [comment]
I'm using this one but has no icons still.. just enemies, cars, dead bodies

**Comment by oCortex** [comment]
I've found it only shows items for the first game, running it before every queue is displaying the items for me.

**Comment by PubgKnown** [comment]
If the icons were missing from my fork it was because there was a bug that caused the item icons to not work if the window was resized. I have fixed that issue.

Also I have optimized the item icon drawing on my fork in commit a few days ago. I ran a test with 10k icons randomly drawn on the window and didn't see any performance drop compared to my old version. I don't think the icons are the cause of any performance issues anymore.

**Comment by SamuelNZ** [comment]
@PubgKnown 

If you use it in offline mode replaying a pcap file then it runs much smoother, still trying to figure out why.

**Comment by pateutz1** [comment]
If you run it on game pc is working good, also is workin smooth, and yes the icons not working if you resize the window

**Comment by SamuelNZ** [comment]
Update if you haven't already.

**Comment by AiYinZiLeGong** [comment]
#2
